### ISSUE TITLE
Adding lein-javadoc to top-level :plugins yields surprising jar contents

### ISSUE THREAD

**Issue by cemerick** [davidsantiago/lein-javadoc#1]
If lein-javadoc is added to the top level `:plugins` vector, then `lein jar` will include the local `tools.jar` and `sa-jdi.jar`, a surprising outcome that has a non-obvious cause once you're hours (or longer) since adding the plugin.

Adding lein-javadoc to a profile, e.g. `:dev`, works well, and doesn't produce any surprises. Perhaps a mention in the setup docs is warranted.

**Comment by davidsantiago** [comment]
OK, wasn't aware of this. Also, it doesn't seem to happen on my project that uses lein-javadoc in the :plugins key. 

Let me first check if there's an actual solution for this.

**Comment by timmc** [comment]
I'm working on a fork that doesn't use lein-jdk-tools and either shells out to javadoc or temporarily loads tools.jar with a classloader.
